### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by h4dr0** [leslie-alldridge/xero-bulk-void-invoice-tool#19]
Did you mean config/.env in localenv.md as it wouldn't load as config.env for me.

I also had to update App.js:24 and index.html:8,10 with localhost URLs and client-id to get this working instead of redirecting me 
to the herokuapp URL.

I ran npm -i in root & client folder, npm run build in client area then npm run dev.  Is there a step I missed to update the above files from the .env?

Thanks
Ateeq

p.s. not a developer so I may be missing the obvious somewhere.

**Comment by leslie-alldridge** [comment]
hey @h4dr0 

with some changes made recently the local dev instructions may be out of date - apologies.

I added the xero specific button in and that caused the problems you've identified in app.js 24 and index.html. For now yes you will need to update those to point to your localhost e.g. `http:localhost:3000`

For the .env file I have `config/.env` on my machine - I'll look to update the instructions
