### ISSUE TITLE
voidly.app HSTS error

### ISSUE THREAD

**Issue by honeyfairy** [leslie-alldridge/xero-bulk-void-invoice-tool#46]
Unable to access this site:

Attackers might be trying to steal your information from voidly.app (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_DATE_INVALID
To get Chrome’s highest level of security, [turn on enhanced protection](chrome-error://chromewebdata/#)
voidly.app normally uses encryption to protect your information. When Chrome tried to connect to voidly.app this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be voidly.app, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit voidly.app right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by leslie-alldridge** [comment]
Thanks i'll take a look

**Comment by leslie-alldridge** [comment]
App has been replaced https://github.com/leslie-alldridge/xero-bulk-void-tool-replacement
