### ISSUE TITLE
Can only retrieve one invoice

### ISSUE THREAD

**Issue by honeyfairy** [leslie-alldridge/xero-bulk-void-invoice-tool#47]
Using this site: https://bulkvoidxero.herokuapp.com/void
I connected, deleted around 70 incoivces.
I still have another 70. But it only shows 1 invoice.

**Comment by leslie-alldridge** [comment]
Thanks i'll take a look

**Comment by leslie-alldridge** [comment]
@honeyfairy does it work if you go to https://voidly.app
