### ISSUE TITLE
Voidly needs to complete certification

### ISSUE THREAD

**Issue by jmfayal** [leslie-alldridge/xero-bulk-void-invoice-tool#56]
Love the app btw. 

I had issues connecting with the old version of the app and I then I found the new voidly page so tried that. Now when I try to connect I get this error: 

"Sorry! Voidly needs to complete certification before they can connect to more Xero organisations.

Please let them know you're keen to try their integration."

Any help connecting would be greatly appreciated!

**Comment by leslie-alldridge** [comment]
Thanks, I've been trying for months to get certified and have decided to throw in the towel. You can fork the repo and supply your own client secret etc to get it going
